BlogMVC/BlogMVC/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Internal;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogMVC.Controllers
{
    public class AboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EFAboutDAlcs());

        // GET: About
        [AllowAnonymous]
        public ActionResult Index(About p)
        {
            var aboutDetail = aboutManager.GetList();

            return View(aboutDetail);
        }
        [AllowAnonymous]
        public PartialViewResult Footer(About p) 
        {
            var footerAboutList = aboutManager.GetList();

            return PartialView(footerAboutList);
        }
        [AllowAnonymous]
        public PartialViewResult MeetTheTeam(Author p)
        {
            AuthorManager authorManager = new AuthorManager(new EFAuthorDaL());

            var authorList = authorManager.GetThreeAuthorList(p);

            return PartialView(authorList);
        }

        [HttpGet]
        public ActionResult AdmniAboutList()
        {
            About aboutList = aboutManager.GetById(1);

            return View(aboutList);
        }

        [HttpPost]
        public ActionResult AdmniAboutList(About p)
        {

            AboutRules validation = new AboutRules();
            
            ValidationResult rules = validation.Validate(p);

            if(rules.IsValid)
            {
                var findAbout = aboutManager.GetById(p.AboutId);
                findAbout.AboutContent1 = p.AboutContent1;
                findAbout.AboutContent2 = p.AboutContent2;
                findAbout.AboutImage1 = p.AboutImage1;
                findAbout.AboutImage2 = p.AboutImage2;

                aboutManager.TUppdate(findAbout);
            }
            else
            {
                foreach(var x in rules.Errors)
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                }
            }


            return View();
        }


    }
}

BlogMVC/BlogMVC/Controllers/MailSubscribeController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogMVC.Controllers
{
    [AllowAnonymous]
    public class MailSubscribeController : Controller
    {
        SubscripeManager subscriberManager = new SubscripeManager(new EFSubscribeDAL());


        [HttpGet]
        public PartialViewResult AddMail()
        {
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult AddMail(Subscribe p) 
        {
            SubscribeRules validations = new SubscribeRules();

            ValidationResult rules = validations.Validate(p);

            if (rules.IsValid)
            {
                subscriberManager.TAdd(p);
            }
            else
            {
                foreach (var rule in rules.Errors) 
                {
                    ModelState.AddModelError(rule.PropertyName, rule.ErrorMessage);
                }
            }

            

            return PartialView();
        }
    }
}

BlogMVC/BlogMVC/Views/About/AdmniAboutList.cshtml
@model EntityLayer.Concrete.About

@{
    ViewBag.Title = "AdmniAboutList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>

<body class="hold-transition sidebar-mini">



    <!-- Main content -->

    <section class="content">

        <div class="row">

            <div class="col-md-12">
                

                <div class="card card-primary">
                


                    <div class="card-header">

                        <h3 class="card-title">Hakkımızda</h3>

                    </div>
                   
                    <form method="post">
                        <div class="card-body">

                            <div class="form-group">

                                <label for="inputName">Hakkımızda Birinci Kısım Resmi</label>
                                @Html.TextBoxFor(x => x.AboutImage1, new { @class = "form-control" })
                                @Html.TextBoxFor(x => x.AboutId, new { @class = "form-control",@type="hidden" })
                                @Html.ValidationMessageFor(x=>x.AboutImage1)

                            </div>

                            <div class="form-group">

                                <label for="inputDescription">Hakkımızda Birinci Kısım Açıklaması</label>
                                @Html.TextAreaFor(x => x.AboutContent1, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.AboutContent1)


                            </div>
                            <div class="form-group">

                                <label for="inputName">Hakkımızda İkinci Kısım Resmi</label>

                                @Html.TextBoxFor(x => x.AboutImage2, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.AboutImage2)

                            </div>

                            <div class="form-group">

                                <label for="inputDescription">Hakkımızda İkinci Kısım Açıklaması</label>

                                @Html.TextAreaFor(x => x.AboutContent2, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.AboutContent2)

                            </div>

                            <div>
                                <button class="btn btn-info">Güncelle</button>
                                <a href="/About/Index/" class="btn btn-info">Sitede Gör</a>

                            </div>



                        </div>
                    </form>
                    <!-- /.card-body -->

                </div>
                
                <!-- /.card -->

            </div>



        </div>



    </section>

</body>

</html>

BlogMVC/BlogMVC/Views/About/Footer.cshtml
@model IEnumerable<EntityLayer.Concrete.About>


<div class="site-footer">
    <div class="container">
        <div class="row mb-5">
            @foreach (var x in Model)
            {
                <div class="col-md-4">
                    <h3 class="footer-heading mb-4">Hakkımızda</h3>
                    <p>@x.AboutContent1</p>
                </div>
            }
            <div class="col-md-3 ml-auto">
                <!-- <h3 class="footer-heading mb-4">Navigation</h3> -->
                <ul class="list-unstyled float-left mr-5">
                    <li><a href="/Blog/Index/">Ana Sayfa</a></li>
                    <li><a href="/About/Index/">Hakkızda</a></li>
                    <li><a href="/Contact/Index">İletişim</a></li>
                    <li><a href="/Login/AuthorLogin/">Yazar girişi</a></li>
                </ul>
                <ul class="list-unstyled float-left">
                    <li><a href="/Blog/BlogByCategory/4/">Teknoloji</a></li>
                    <li><a href="/Blog/BlogByCategory/2/">Kültür & Sanat</a></li>
                    <li><a href="/Blog/BlogByCategory/1/">Yazılım</a></li>
                    <li><a href="/Blog/BlogByCategory/5/">Film & Dİzi</a></li>
                    <li><a href="/Blog/BlogByCategory/3/">Seyahat</a></li>
                </ul>
            </div>
            <div class="col-md-4">


                <div>
                    <h3 class="footer-heading mb-4">Sosyal Medya Hesaplarımız</h3>
                    <p>
                        <a href="#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
                        <a href="#"><span class="icon-twitter p-2"></span></a>
                        <a href="#"><span class="icon-instagram p-2"></span></a>
                        <a href="#"><span class="icon-rss p-2"></span></a>
                        <a href="#"><span class="icon-envelope p-2"></span></a>
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <p>
          
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> Tüm Haklar Saklıdır
                
                </p>
            </div>
        </div>
    </div>
</div>

BlogMVC/BlogMVC/Views/About/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.About>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}

<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('/miniblog/images/img_4.jpg');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <h1 class="">Hakkımızda</h1>
                    <p class="lead mb-4 text-white">Bizi daha yakından tanımak ister  misiniz ?</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            @foreach (var x in Model)
            {
            <div class="col-md-6 order-md-2">
                <img src="@x.AboutImage1" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-5 mr-auto order-md-1">
                <h2>Hakkımızda</h2>
                <p>@x.AboutContent1</p>
                @*<ul class="ul-check list-unstyled success">
                    <li>Onsectetur adipisicing elit</li>
                    <li>Dolorem saepe non eligendi possimus</li>
                    <li>Voluptate odit corrupti vitae</li>
                </ul>*@
            </div>
            }
        </div>
            
    </div>
</div>

@Html.Action("MeetTheTeam", "About")

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            @foreach (var x in Model)
            {
            <div class="col-md-6">
                <img src="@x.AboutImage2" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-5 ml-auto">
                <h2>Neler Yapıyoruz</h2>
                <p class="mb-4">@x.AboutContent2</p>

                @*<ul class="ul-check list-unstyled success">
                    <li>Onsectetur adipisicing elit</li>
                    <li>Dolorem saepe non eligendi possimus</li>
                    <li>Voluptate odit corrupti vitae</li>
                </ul>*@
            </div>
            }
        </div>
    </div>
</div>

@Html.Action("AddMail","MailSubscribe")

@Html.Action("Footer", "About")

BlogMVC/BlogMVC/Views/About/MeetTheTeam.cshtml
@model IEnumerable<EntityLayer.Concrete.Author>

<div class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-5 text-center">
                <h2>Yazarlar</h2>
                <p>Aşağıda sitemizde yer alan üç en başarılı üç yazarımızın bilgilerine ulaşabilirsiniz. Sizde yazar olmak isterseniz iletişim kısmından bize ulaşın</p>
            </div>
        </div>
        <div class="row">
            @foreach (var x in Model)
            {
            <div class="col-md-6 col-lg-4 mb-5 text-center">
                <img src="@x.AuthorImage" alt="Image" class="img-fluid w-50 rounded-circle mb-4" style="height:200px; width:150px">
                <h2 class="mb-3 h5">@x.AuthorName</h2>
                <p>@x.AuthorAbout</p>

                <p class="mt-5">
                    <a href="#" class="p-3"><span class="icon-facebook"></span></a>
                    <a href="#" class="p-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="p-3"><span class="icon-twitter"></span></a>
                </p>
            </div>
            }

        </div>
    </div>
</div>